CREATE TABLE menus
	(
		`id`         INTEGER PRIMARY KEY AUTOINCREMENT,
		`label`      TEXT NOT NULL,
		`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
		`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP
	);