CREATE TABLE IF NOT EXISTS users
	(
		`id`         INT          NOT NULL AUTO_INCREMENT,
		`email`      VARCHAR(255) NOT NULL,
		`password`   VARCHAR(255) NOT NULL,
		`is_active`  BOOLEAN DEFAULT true,
		`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		PRIMARY KEY (`id`)
	);